services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: hello_django_prod
    container_name: hello_django_prod
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: hello_django_db_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 1338:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
